---
    token: ""
    SuperUser: 
        - 
    Users: 
        - 
        - 
        
    Socket_connection: # Config for the socket connection, for data transfer between processes
        Host:
          IP: 127.0.0.4
          Port: 65432

        Client:
          IP: 127.0.0.2
          Port: 65432